name: Deploy Docusaurus Website

on:
  push:
    branches:
      - main # Change 'main' to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure this matches your Docusaurus version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the site
      - name: Build the site
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_SECRET }}
          publish_dir: ./build
